name: Generate contributors

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - master
      - main
      - develop

jobs:
  generate-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contributors
        uses: gouef/create-contributors-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
