name: Run tests and upload coverage

on:
  pull_request:
    types: [opened, synchronize, edited]
  push:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: gouef/github-lib-template/.github/workflows/shared_tests.yml@main
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      slug: ${{ github.repository }}