name: Run tests and upload coverage

on:
  push

jobs:
  test:
    uses: gouef/github-lib-template/.github/workflows/shared_tests.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      slug: ${{ github.repository }}